### PR TITLE
added something in README

### PR DESCRIPTION
**Pull request by flaing**
something

### CODE REVIEW

**Comment by flaing** [comment]
a: aaa
b: ccc

**Comment by paulkoegel** [comment]
why?

**Comment by flaing** [comment]
sorry, this is just a stupid demo for a free git workflow tutorial. I wanted to show how commit tree looked like to people then.

**Comment by flaing** [comment]
operation error,  sorry.

**Comment by paulkoegel** [comment]
alright. closing this pull request then.
thanks for checking out Omingard!

**Pull request closed without merging**
